---
- name: Create ENV file for {{ container_name }}_container.service
  template:
    src: "{{ template_env_path }}"
    dest: "{{ sysconf_dir }}/{{ container_name }}"
    owner: root
    group: root
    mode: '0600'
  when: container_env is defined
  notify: restart container {{ container_name }}

- name: Pull image {{ container_image }}
  docker_image:
    name: '{{ container_image }}'
    force: true
  when: container_docker_pull

# TODO: Add handler to restart service after new image has been pulled
- name: Create unit {{ container_name }}_container.service
  template:
    src: "{{ template_unit_path }}"
    dest: /etc/systemd/system/{{ container_name }}_container.service
    owner: root
    group: root
    mode: '0644'
  notify: restart container {{ container_name }}

- name: Enable and start {{ container_name }}
  systemd:
    name: '{{ container_name }}_container.service'
    daemon_reload: true
    enabled: "{{ service_enabled }}"
    masked: "{{ service_masked }}"
    state: "{{ service_state }}"
  register: enable_and_start
